// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/content_page.dart' as a2;
import 'app/home_page.dart' as a1;
import 'app/login_page.dart' as a0;
import 'app/quiz_page.dart' as a3;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.LoginPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/content',
        uri: Uri.parse('/content'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.ContentPage(),
        ),
      ),
      RouteEntity(
        key: '/quiz',
        uri: Uri.parse('/quiz'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.QuizPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  login: '/login',
  home: '/home',
  content: '/content',
  quiz: '/quiz',
);
